import type { CSSProperties } from "react"
import { colors, fonts } from "@/styles/theme"

export const styles: Record<string, CSSProperties> = {
  root: {
    position: "relative",
    minHeight: "100vh",
    background: colors.bg,
    color: colors.text,
    fontFamily: fonts.mono,
    fontSize: "12px",
    overflow: "hidden",
  },
  noise: {
    position: "fixed",
    inset: 0,
    backgroundImage:
      "url(\"data:image/svg+xml,%3Csvg viewBox='0 0 200 200' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='0.04'/%3E%3C/svg%3E\")",
    backgroundRepeat: "repeat",
    backgroundSize: "200px",
    pointerEvents: "none",
    zIndex: 9999,
    opacity: 0.35,
  },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "0 24px",
    height: "48px",
    borderBottom: `1px solid ${colors.border2}`,
    background: colors.surface,
    position: "sticky",
    top: 0,
    zIndex: 100,
  },
  headerLogo: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  logoMark: {
    fontSize: "18px",
    color: colors.accent,
  },
  logoText: {
    fontSize: "13px",
    fontWeight: 700,
    letterSpacing: "4px",
    color: colors.textStrong,
    fontFamily: fonts.display,
  },
  flowNav: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    fontSize: "10px",
    letterSpacing: "2px",
    color: colors.textMuted,
  },
  flowStep: { color: colors.textSubtle },
  flowArrow: { color: colors.textFaint },
  headerRight: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  clock: {
    color: colors.accent,
    fontWeight: 600,
    letterSpacing: "2px",
  },
  themeToggle: {
    border: `1px solid ${colors.border2}`,
    background: "transparent",
    color: colors.textMuted,
    padding: "4px 8px",
    cursor: "pointer",
    fontSize: "10px",
    letterSpacing: "1px",
  },
  main: {
    background: colors.panel2,
    minHeight: "calc(100vh - 48px)",
  },
  column: {
    background: colors.bg,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },
  colInbox: {},
  colPriority: { overflow: "auto" },
  colStudio: {},
  colStudioCollapsed: {
    overflow: "hidden",
  },
  colHeader: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "12px 16px",
    borderBottom: `1px solid ${colors.divider}`,
    background: colors.surface,
    position: "sticky",
    top: 0,
    zIndex: 10,
  },
  colIcon: {
    color: colors.accent,
    fontSize: "14px",
  },
  colTitle: {
    fontWeight: 700,
    letterSpacing: "3px",
    color: colors.textStrong,
    fontSize: "11px",
  },
  colSubtitle: {
    marginLeft: "auto",
    color: colors.textFaint,
    fontSize: "10px",
    letterSpacing: "2px",
  },
  colHeaderAction: {
    border: `1px solid ${colors.border2}`,
    background: "transparent",
    color: colors.textMuted,
    padding: "2px 6px",
    cursor: "pointer",
    fontSize: "10px",
    letterSpacing: "1px",
    flexShrink: 0,
  },
  badge: {
    marginLeft: "auto",
    background: colors.danger,
    color: colors.textStrong,
    borderRadius: "2px",
    padding: "1px 6px",
    fontSize: "10px",
    fontWeight: 700,
  },
  eventList: {
    flex: 1,
    overflowY: "auto",
    padding: "8px",
  },
  eventCard: {
    width: "100%",
    display: "flex",
    gap: "10px",
    padding: "10px",
    marginBottom: "4px",
    background: colors.panel,
    border: `1px solid ${colors.border}`,
    cursor: "pointer",
    transition: "border-color 0.15s",
    textAlign: "left",
  },
  eventCardActive: {
    borderColor: colors.accent,
    background: colors.successBg,
  },
  eventIcon: {
    fontSize: "12px",
    marginTop: "2px",
    flexShrink: 0,
  },
  eventBadge: {
    marginTop: "1px",
    flexShrink: 0,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "2px 8px",
    borderRadius: "999px",
    border: "1px solid",
    fontSize: "9px",
    fontWeight: 700,
    letterSpacing: "1px",
    lineHeight: 1.2,
    whiteSpace: "nowrap",
  },
  eventBody: {
    flex: 1,
    minWidth: 0,
  },
  eventSignal: {
    fontWeight: 600,
    color: colors.text,
    lineHeight: 1.4,
    marginBottom: "4px",
  },
  eventMeta: {
    display: "flex",
    justifyContent: "space-between",
    gap: "8px",
  },
  eventSource: {
    color: colors.textMuted,
    fontSize: "10px",
  },
  eventTime: {
    color: colors.textFaint,
    fontSize: "10px",
  },
  inboxEmpty: {
    height: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "24px 12px",
    textAlign: "center",
  },
  inboxGuide: {
    marginTop: "12px",
    display: "grid",
    gap: "6px",
    justifyItems: "center",
  },
  inboxGuideStep: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    color: colors.textMuted,
    fontSize: "11px",
  },
  inboxGuideNum: {
    width: "18px",
    height: "18px",
    borderRadius: "999px",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    border: `1px solid ${colors.border2}`,
    color: colors.textMuted,
    fontSize: "10px",
    lineHeight: 1,
    flexShrink: 0,
  },
  wuList: {
    padding: "8px",
    display: "flex",
    flexDirection: "column",
    gap: "4px",
  },
  wuCard: {
    width: "100%",
    display: "flex",
    gap: "12px",
    padding: "12px",
    background: colors.panel,
    border: `1px solid ${colors.border}`,
    cursor: "pointer",
    transition: "border-color 0.15s",
    textAlign: "left",
  },
  wuCardSelected: {
    borderColor: colors.accent,
    background: colors.successBg,
  },
  wuRoi: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    minWidth: "44px",
    gap: "2px",
  },
  wuRoiNum: {
    fontSize: "22px",
    fontWeight: 700,
    color: colors.accent,
    lineHeight: 1,
  },
  wuRoiLabel: {
    fontSize: "9px",
    color: colors.textMuted,
    letterSpacing: "2px",
  },
  wuRank: {
    fontSize: "10px",
    color: colors.textFaint,
  },
  wuRoiMini: {
    marginTop: "6px",
    width: "100%",
    display: "flex",
    flexDirection: "column",
    gap: "3px",
  },
  wuRoiMiniBars: {
    display: "flex",
    gap: "3px",
  },
  wuMiniBar: {
    flex: 1,
    height: "4px",
    background: colors.border,
    borderRadius: "2px",
    overflow: "hidden",
  },
  wuMiniFill: {
    height: "100%",
    background: colors.accent,
    borderRadius: "2px",
  },
  wuRoiMiniText: {
    fontSize: "9px",
    color: colors.textMuted,
    letterSpacing: "0.5px",
    lineHeight: 1.2,
  },
  wuInfo: {
    flex: 1,
    minWidth: 0,
  },
  wuTitleRow: {
    display: "flex",
    justifyContent: "space-between",
    marginBottom: "4px",
    gap: "8px",
  },
  wuTitle: {
    fontWeight: 700,
    color: colors.textStrong,
    fontSize: "12px",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  wuStatus: {
    fontSize: "9px",
    border: "1px solid",
    padding: "1px 5px",
    flexShrink: 0,
    height: "fit-content",
  },
  wuProblem: {
    color: colors.textSubtle,
    fontSize: "11px",
    marginBottom: "6px",
    lineHeight: 1.4,
  },
  wuMeta: {
    display: "flex",
    gap: "12px",
    color: colors.textMuted,
    fontSize: "10px",
    flexWrap: "wrap",
  },
  wuDetail: {
    margin: "8px",
    padding: "16px",
    background: colors.surface,
    border: `1px solid ${colors.border2}`,
    flex: 1,
    overflow: "auto",
  },
  detailHeader: { marginBottom: "12px" },
  detailTitle: {
    display: "block",
    fontSize: "14px",
    fontWeight: 700,
    color: colors.textStrong,
    marginBottom: "10px",
  },
  statusRow: {
    display: "flex",
    gap: "4px",
    flexWrap: "wrap",
  },
  statusBtn: {
    padding: "3px 10px",
    background: "transparent",
    border: `1px solid ${colors.border2}`,
    color: colors.textMuted,
    cursor: "pointer",
    fontSize: "10px",
    letterSpacing: "1px",
    fontFamily: "inherit",
  },
  roiBreakdown: {
    background: colors.panel,
    border: `1px solid ${colors.border2}`,
    padding: "10px",
    marginBottom: "12px",
  },
  roiLabel: {
    color: colors.accent,
    fontWeight: 700,
    fontSize: "13px",
    display: "block",
    marginBottom: "8px",
  },
  roiFactors: {
    display: "flex",
    gap: "16px",
    flexWrap: "wrap",
  },
  roiFeedbackRow: {
    marginTop: "10px",
    display: "flex",
    gap: "6px",
    justifyContent: "flex-end",
    flexWrap: "wrap",
  },
  roiFeedbackBtn: {
    padding: "4px 10px",
    background: "transparent",
    border: `1px solid ${colors.border2}`,
    color: colors.textMuted,
    cursor: "pointer",
    fontSize: "10px",
    letterSpacing: "1px",
  },
  roiFeedbackPanel: {
    marginTop: "10px",
    padding: "10px",
    background: colors.surface,
    border: `1px solid ${colors.border}`,
  },
  roiFeedbackGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: "8px",
    marginTop: "8px",
  },
  roiFeedbackField: {
    display: "flex",
    flexDirection: "column",
    gap: "4px",
  },
  roiFeedbackLabel: {
    color: colors.textMuted,
    fontSize: "9px",
    letterSpacing: "2px",
  },
  roiFeedbackInput: {
    background: colors.panel,
    border: `1px solid ${colors.border}`,
    color: colors.text,
    padding: "6px 8px",
    outline: "none",
  },
  roiFeedbackActions: {
    marginTop: "10px",
    display: "flex",
    gap: "6px",
    justifyContent: "flex-end",
    flexWrap: "wrap",
  },
  modalOverlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(0, 0, 0, 0.55)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "16px",
    zIndex: 10000,
  },
  modal: {
    width: "100%",
    maxWidth: "440px",
    background: colors.surface,
    border: `1px solid ${colors.border2}`,
    padding: "14px",
    boxShadow: "0 20px 60px rgba(0,0,0,0.45)",
  },
  modalTitle: {
    color: colors.textStrong,
    fontSize: "13px",
    fontWeight: 700,
    marginBottom: "10px",
  },
  modalOptions: {
    display: "grid",
    gap: "6px",
  },
  modalOption: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    gap: "10px",
    padding: "9px 10px",
    background: colors.panel,
    border: `1px solid ${colors.border}`,
    cursor: "pointer",
    textAlign: "left",
    color: colors.text,
    fontSize: "12px",
  },
  modalOptionSelected: {
    borderColor: colors.accent,
    background: colors.successBg,
  },
  modalRadio: {
    width: "16px",
    textAlign: "center",
    flexShrink: 0,
    color: colors.textMuted,
  },
  modalOptionText: {
    flex: 1,
  },
  modalOther: {
    marginTop: "10px",
  },
  modalOtherLabel: {
    color: colors.textMuted,
    fontSize: "10px",
    letterSpacing: "1px",
    marginBottom: "6px",
  },
  modalInput: {
    width: "100%",
    background: colors.panel,
    border: `1px solid ${colors.border}`,
    color: colors.text,
    padding: "8px 10px",
    outline: "none",
  },
  modalFooter: {
    marginTop: "12px",
    display: "flex",
    gap: "8px",
    justifyContent: "flex-end",
  },
  modalBtn: {
    padding: "6px 12px",
    background: "transparent",
    border: `1px solid ${colors.border2}`,
    color: colors.textMuted,
    cursor: "pointer",
    fontSize: "10px",
    letterSpacing: "1px",
  },
  modalBtnPrimary: {
    borderColor: colors.accentBorder,
    color: colors.accent,
  },
  modalBtnDisabled: {
    opacity: 0.5,
    cursor: "not-allowed",
  },
  roiFactor: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    minWidth: "52px",
  },
  roiFactorKey: {
    color: colors.textMuted,
    fontSize: "9px",
    letterSpacing: "1px",
  },
  roiFactorVal: {
    color: colors.text,
    fontWeight: 700,
    fontSize: "16px",
  },
  detailGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: "8px",
    marginBottom: "12px",
  },
  detailField: {
    background: colors.panel,
    padding: "8px",
    border: `1px solid ${colors.border}`,
  },
  detailFieldLabel: {
    color: colors.textMuted,
    fontSize: "9px",
    letterSpacing: "2px",
    marginBottom: "4px",
  },
  detailFieldValue: {
    color: colors.text,
    fontSize: "11px",
    lineHeight: 1.4,
  },
  taskSection: { marginTop: "8px" },
  taskHeader: {
    color: colors.textMuted,
    fontSize: "9px",
    letterSpacing: "3px",
    marginBottom: "6px",
  },
  taskItem: {
    width: "100%",
    display: "flex",
    gap: "8px",
    padding: "7px 0",
    borderBottom: `1px solid ${colors.border}`,
    cursor: "pointer",
    color: colors.text,
    fontSize: "11px",
    textAlign: "left",
  },
  taskCheck: {
    color: colors.accent,
    flexShrink: 0,
  },
  studioTabs: {
    display: "flex",
    flexDirection: "column",
    gap: "2px",
    padding: "8px",
    borderBottom: `1px solid ${colors.border}`,
  },
  studioCollapsedButton: {
    width: "100%",
    height: "100%",
    background: colors.surface,
    border: "none",
    color: colors.textMuted,
    cursor: "pointer",
    writingMode: "vertical-rl",
    transform: "rotate(180deg)",
    letterSpacing: "3px",
    fontSize: "10px",
  },
  studioTab: {
    width: "100%",
    display: "flex",
    gap: "8px",
    alignItems: "center",
    padding: "7px 10px",
    background: colors.panel,
    border: "1px solid transparent",
    cursor: "pointer",
    textAlign: "left",
  },
  studioTabActive: {
    borderColor: colors.accent,
    background: "#0D1A0D",
  },
  studioTabMode: {
    color: colors.textMuted,
    fontSize: "9px",
    letterSpacing: "2px",
    flexShrink: 0,
  },
  studioTabTitle: {
    color: colors.text,
    fontSize: "11px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  newDocBtn: {
    background: "transparent",
    border: `1px dashed ${colors.border2}`,
    color: colors.textMuted,
    padding: "6px",
    cursor: "pointer",
    fontFamily: "inherit",
    fontSize: "10px",
    letterSpacing: "2px",
    textAlign: "center",
  },
  studioEditor: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    padding: "12px",
    gap: "8px",
    minHeight: "280px",
  },
  studioDocMeta: {
    display: "flex",
    gap: "8px",
    alignItems: "center",
    flexWrap: "wrap",
  },
  studioModeTag: {
    background: colors.accentSurface,
    border: `1px solid ${colors.accentSurfaceBorder}`,
    color: colors.accent,
    fontSize: "9px",
    letterSpacing: "2px",
    padding: "2px 6px",
  },
  studioDocTitle: {
    color: colors.textSubtle,
    fontSize: "11px",
  },
  studioTextarea: {
    flex: 1,
    background: colors.surface,
    border: `1px solid ${colors.divider}`,
    color: colors.text,
    fontFamily: fonts.mono,
    fontSize: "12px",
    lineHeight: 1.7,
    padding: "12px",
    resize: "none",
    outline: "none",
    minHeight: "200px",
  },
  studioActions: {
    display: "flex",
    gap: "6px",
  },
  actionBtn: {
    flex: 1,
    background: "transparent",
    border: `1px solid ${colors.accentBorder}`,
    color: colors.accent,
    padding: "7px",
    cursor: "pointer",
    fontFamily: "inherit",
    fontSize: "10px",
    letterSpacing: "1px",
  },
  studioEmpty: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "32px 20px",
    color: colors.textMuted,
    fontSize: "12px",
  },
  studioEmptyTitle: {
    color: colors.textSubtle,
    fontSize: "13px",
    marginBottom: "8px",
    textAlign: "center",
  },
  studioEmptyBody: {
    color: colors.textMuted,
    textAlign: "center",
    lineHeight: 1.5,
  },
  flowIndicator: {
    padding: "16px",
    borderTop: `1px solid ${colors.border}`,
    display: "flex",
    flexDirection: "column",
    gap: "0",
  },
  flowIndicatorTitle: {
    color: colors.textFaint,
    fontSize: "9px",
    letterSpacing: "3px",
    marginBottom: "10px",
  },
  flowIndicatorStep: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    position: "relative",
  },
  flowDot: {
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    marginBottom: "2px",
  },
  flowStepLabel: {
    color: colors.textMuted,
    fontSize: "10px",
    marginLeft: "16px",
    marginTop: "-18px",
  },
  flowConnector: {
    color: colors.textFaint,
    marginLeft: "3px",
    lineHeight: "1.8",
    fontSize: "12px",
  },
  emptyStateTitle: {
    color: colors.textSubtle,
    fontSize: "13px",
    marginBottom: "8px",
  },
  emptyStateBody: {
    color: colors.textMuted,
    lineHeight: 1.5,
  },
}
